CREATE TABLE `gs`.`orn_images` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Hashkey` VARCHAR(255) NULL DEFAULT NULL,
  `Image` BLOB NULL DEFAULT NULL,
  `Format` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`Id`));


ALTER TABLE `gs`.`orn_images` 
CHANGE COLUMN `Format` `Format` VARCHAR(500) NULL DEFAULT NULL ,
ADD COLUMN `Path` VARCHAR(500) NULL DEFAULT NULL AFTER `Format`,
ADD COLUMN `StorageMode` VARCHAR(100) NOT NULL AFTER `Path`,
ADD COLUMN `Optional` TEXT NULL DEFAULT NULL AFTER `StorageMode`;
