CREATE TABLE `gs`.`orn_images` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `HashKey` VARCHAR(255) NULL DEFAULT NULL,
  `Image` BLOB NULL DEFAULT NULL,
  `Format` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`Id`));
