version: "3.9"
services:
  # frontend:
  #   image: "gs-client-prj:2"
  #   ports:
  #     - "3004:3000"
  backend:
    image: "gs-server:1"
    ports: 
      - "3102:3102"
    depends_on: 
      - db
    volumes:
      - gs-server-logs:/usr/src/app/server/logs
    restart: always
  db:
    command: mysqld --default-authentication-plugin=mysql_native_password
    environment: 
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    image: "mysql:latest"
    ports:
      - "3307:3306"
    volumes: 
      - gs-mysql-data:/var/lib/mysql
    restart: always
volumes:
  gs-mysql-data:
    external: true
  gs-server-logs:
    external: true