version: "3.9"
services:
  frontend:
    image: "gs-client-img:1"
    ports:
      - "3004:3000"
  backend:
    image: "gs-server-img:1"
    ports: 
      - "3102:3003"
    depends_on: 
      - db
    volumes:
      - gs-server-logs:/usr/src/app/server/logs
    restart: unless-stopped
  db:
    command: mysqld --default-authentication-plugin=mysql_native_password
    environment: 
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    image: "mysql:latest"
    ports:
      - "3307:3306"
    volumes: 
      - gs-mysql-data:/var/lib/mysql
    restart: unless-stopped
volumes:
  gs-mysql-data:
    external: true
  gs-server-logs:
    external: true